builds:
  - binary: iscrt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '6'
      - '7'
    ignore:
      - goos: darwin
        goarch: arm
archives:
  - replacements:
      '386': i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
nfpms:
  - id: linux_packages
    replacements:
      '386': i386
      amd64: x86_64
    homepage: https://github.com/iminaii/iscrt
    maintainer: iminaii
    description: A secret manager for the command-line with .env file support (fork of scrt)
    license: Apache 2.0
    formats:
      - deb
      - rpm
    section: devel
checksum:
  name_template: 'checksums.txt'
  ids:
    - default
snapshot:
  name_template: '{{ .RawVersion }}-dev-{{ .ShortCommit }}'
release:
  github:
    owner: iminaii
    name: iscrt
  ids:
    - default
