package cmd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestParseEnvFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".env")

	content := `# Database config
DB_HOST=localhost
DB_PORT=5432

# API keys
API_KEY="sk-abc123"
SINGLE_QUOTED='literal-value'
export EXPORTED_VAR=exported-value
BASE64_VALUE=dGVzdA==
EMPTY_VALUE=
URL=https://example.com/path?q=1&r=2
`

	os.WriteFile(path, []byte(content), 0644)

	vars, err := parseEnvFile(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	tests := map[string]string{
		"DB_HOST":       "localhost",
		"DB_PORT":       "5432",
		"API_KEY":       "sk-abc123",
		"SINGLE_QUOTED": "literal-value",
		"EXPORTED_VAR":  "exported-value",
		"BASE64_VALUE":  "dGVzdA==",
		"EMPTY_VALUE":   "",
		"URL":           "https://example.com/path?q=1&r=2",
	}

	if len(vars) != len(tests) {
		t.Fatalf("expected %d vars, got %d: %v", len(tests), len(vars), vars)
	}

	for k, expected := range tests {
		got, ok := vars[k]
		if !ok {
			t.Errorf("missing key: %s", k)
			continue
		}
		if got != expected {
			t.Errorf("%s: expected %q, got %q", k, expected, got)
		}
	}
}

func TestParseEnvFileNotFound(t *testing.T) {
	_, err := parseEnvFile("/nonexistent/.env")
	if err == nil {
		t.Fatal("expected error for missing file")
	}
}

func TestWriteEnvFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".env")

	vars := map[string]string{
		"DB_HOST": "localhost",
		"API_KEY": "sk-abc123",
	}

	err := writeEnvFile(path, vars, "test-project")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("failed to read written file: %v", err)
	}

	s := string(content)

	if !strings.Contains(s, "# Generated by iscrt") {
		t.Error("missing header comment")
	}
	if !strings.Contains(s, "# Project: test-project") {
		t.Error("missing project comment")
	}
	if !strings.Contains(s, "DB_HOST=localhost") {
		t.Error("missing DB_HOST")
	}
	if !strings.Contains(s, "API_KEY=sk-abc123") {
		t.Error("missing API_KEY")
	}
}
