package cmd

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
)

// parseEnvFile reads a .env file and returns key-value pairs.
// Handles: comments, blank lines, quoted values, export prefix, values with =.
func parseEnvFile(path string) (map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	vars := make(map[string]string)
	scanner := bufio.NewScanner(f)

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Skip blank lines and comments
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Strip export prefix
		if strings.HasPrefix(line, "export ") {
			line = strings.TrimPrefix(line, "export ")
			line = strings.TrimSpace(line)
		}

		// Split on first =
		idx := strings.Index(line, "=")
		if idx < 0 {
			continue
		}

		key := strings.TrimSpace(line[:idx])
		val := line[idx+1:]

		// Strip surrounding quotes
		if len(val) >= 2 {
			if (val[0] == '"' && val[len(val)-1] == '"') ||
				(val[0] == '\'' && val[len(val)-1] == '\'') {
				val = val[1 : len(val)-1]
			}
		}

		vars[key] = val
	}

	if err := scanner.Err(); err != nil {
		return nil, err
	}

	return vars, nil
}

// writeEnvFile writes key-value pairs to a .env file with a header.
// writeEnvFile writes key-value pairs to a .env file with a header.
// Uses 0600 permissions to protect secret values.
func writeEnvFile(path string, vars map[string]string, project string) error {
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return err
	}

	w := bufio.NewWriter(f)

	// Header
	fmt.Fprintf(w, "# Generated by iscrt\n")
	fmt.Fprintf(w, "# Project: %s\n", project)
	fmt.Fprintf(w, "# Date: %s\n", time.Now().Format("2006-01-02"))
	fmt.Fprintln(w)

	// Sort keys for deterministic output
	keys := make([]string, 0, len(vars))
	for k := range vars {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		fmt.Fprintf(w, "%s=%s\n", k, vars[k])
	}

	if err := w.Flush(); err != nil {
		f.Close()
		return err
	}
	return f.Close()
}
